import { BullMonitorExpress } from '@bull-monitor/express';
import { InjectQueue } from '@nestjs/bull';
import { Injectable } from '@nestjs/common';
import { Queue } from 'bull';
import { BullAdapter } from '@bull-monitor/root/dist/bull-adapter';

@Injectable()
export class BullMonitorService extends BullMonitorExpress {
  constructor(
    @InjectQueue('OneMinuteCandle_Fetches') OneMinuteCandleQueue_Fetches: Queue,
    @InjectQueue('ThreeMinutesCandle_Fetches') ThreeMinutesCandleQueue_Fetches: Queue,
    @InjectQueue('FiveMinutesCandle_Fetches') FiveMinutesCandleQueue_Fetches: Queue,
    @InjectQueue('FifteenMinutesCandle_Fetches') FifteenMinutesCandleQueue_Fetches: Queue,
    @InjectQueue('ThirtyMinutesCandle_Fetches') ThirtyMinutesCandleQueue_Fetches: Queue,
    @InjectQueue('OneHourCandle_Fetches') OneHourCandleQueue_Fetches: Queue,
    @InjectQueue('TwoHoursCandle_Fetches') TwoHourCandleQueue_Fetches: Queue,
    @InjectQueue('FourHoursCandle_Fetches') FourHourCandleQueue_Fetches: Queue,
    @InjectQueue('SixHoursCandle_Fetches') SixHourCandleQueue_Fetches: Queue,
    @InjectQueue('EightHoursCandle_Fetches') EightHourCandleQueue_Fetches: Queue,
    @InjectQueue('TwelveHoursCandle_Fetches') TwelveHourCandleQueue_Fetches: Queue,
    @InjectQueue('OneDayCandle_Fetches') OneDayCandleQueue_Fetches: Queue,
    @InjectQueue('ThreeDaysCandle_Fetches') ThreeDayCandleQueue_Fetches: Queue,
    @InjectQueue('OneWeekCandle_Fetches') OneWeekCandleQueue_Fetches: Queue,
    @InjectQueue('OneMonthCandle_Fetches') OneMonthCandleQueue_Fetches: Queue,

    @InjectQueue('OneMinuteCandle_Calculations') OneMinuteCandleQueue_Calculations: Queue,
    @InjectQueue('ThreeMinutesCandle_Calculations') ThreeMinutesCandleQueue_Calculations: Queue,
    @InjectQueue('FiveMinutesCandle_Calculations') FiveMinutesCandleQueue_Calculations: Queue,
    @InjectQueue('FifteenMinutesCandle_Calculations') FifteenMinutesCandleQueue_Calculations: Queue,
    @InjectQueue('ThirtyMinutesCandle_Calculations') ThirtyMinutesCandleQueue_Calculations: Queue,
    @InjectQueue('OneHourCandle_Calculations') OneHourCandleQueue_Calculations: Queue,
    @InjectQueue('TwoHoursCandle_Calculations') TwoHourCandleQueue_Calculations: Queue,
    @InjectQueue('FourHoursCandle_Calculations') FourHourCandleQueue_Calculations: Queue,
    @InjectQueue('SixHoursCandle_Calculations') SixHourCandleQueue_Calculations: Queue,
    @InjectQueue('EightHoursCandle_Calculations') EightHourCandleQueue_Calculations: Queue,
    @InjectQueue('TwelveHoursCandle_Calculations') TwelveHourCandleQueue_Calculations: Queue,
    @InjectQueue('OneDayCandle_Calculations') OneDayCandleQueue_Calculations: Queue,
    @InjectQueue('ThreeDaysCandle_Calculations') ThreeDayCandleQueue_Calculations: Queue,
    @InjectQueue('OneWeekCandle_Calculations') OneWeekCandleQueue_Calculations: Queue,
    @InjectQueue('OneMonthCandle_Calculations') OneMonthCandleQueue_Calculations: Queue,


    @InjectQueue('OneMinuteCandle_Preprocessings') OneMinuteCandleQueue_Preprocessings: Queue,
    @InjectQueue('ThreeMinutesCandle_Preprocessings') ThreeMinutesCandleQueue_Preprocessings: Queue,
    @InjectQueue('FiveMinutesCandle_Preprocessings') FiveMinutesCandleQueue_Preprocessings: Queue,
    @InjectQueue('FifteenMinutesCandle_Preprocessings') FifteenMinutesCandleQueue_Preprocessings: Queue,
    @InjectQueue('ThirtyMinutesCandle_Preprocessings') ThirtyMinutesCandleQueue_Preprocessings: Queue,
    @InjectQueue('OneHourCandle_Preprocessings') OneHourCandleQueue_Preprocessings: Queue,
    @InjectQueue('TwoHoursCandle_Preprocessings') TwoHourCandleQueue_Preprocessings: Queue,
    @InjectQueue('FourHoursCandle_Preprocessings') FourHourCandleQueue_Preprocessings: Queue,
    @InjectQueue('SixHoursCandle_Preprocessings') SixHourCandleQueue_Preprocessings: Queue,
    @InjectQueue('EightHoursCandle_Preprocessings') EightHourCandleQueue_Preprocessings: Queue,
    @InjectQueue('TwelveHoursCandle_Preprocessings') TwelveHourCandleQueue_Preprocessings: Queue,
    @InjectQueue('OneDayCandle_Preprocessings') OneDayCandleQueue_Preprocessings: Queue,
    @InjectQueue('ThreeDaysCandle_Preprocessings') ThreeDayCandleQueue_Preprocessings: Queue,
    @InjectQueue('OneWeekCandle_Preprocessings') OneWeekCandleQueue_Preprocessings: Queue,
    @InjectQueue('OneMonthCandle_Preprocessings') OneMonthCandleQueue_Preprocessings: Queue,
  ) {
    super({
      queues: [
        new BullAdapter(OneMinuteCandleQueue_Fetches),
        new BullAdapter(ThreeMinutesCandleQueue_Fetches),
        new BullAdapter(FiveMinutesCandleQueue_Fetches),
        new BullAdapter(FifteenMinutesCandleQueue_Fetches),
        new BullAdapter(ThirtyMinutesCandleQueue_Fetches),
        new BullAdapter(OneHourCandleQueue_Fetches),
        new BullAdapter(TwoHourCandleQueue_Fetches),
        new BullAdapter(FourHourCandleQueue_Fetches),
        new BullAdapter(SixHourCandleQueue_Fetches),
        new BullAdapter(EightHourCandleQueue_Fetches),
        new BullAdapter(TwelveHourCandleQueue_Fetches),
        new BullAdapter(OneDayCandleQueue_Fetches),
        new BullAdapter(ThreeDayCandleQueue_Fetches),
        new BullAdapter(OneWeekCandleQueue_Fetches),
        new BullAdapter(OneMonthCandleQueue_Fetches),

        new BullAdapter(OneMinuteCandleQueue_Calculations),
        new BullAdapter(ThreeMinutesCandleQueue_Calculations),
        new BullAdapter(FiveMinutesCandleQueue_Calculations),
        new BullAdapter(FifteenMinutesCandleQueue_Calculations),
        new BullAdapter(ThirtyMinutesCandleQueue_Calculations),
        new BullAdapter(OneHourCandleQueue_Calculations),
        new BullAdapter(TwoHourCandleQueue_Calculations),
        new BullAdapter(FourHourCandleQueue_Calculations),
        new BullAdapter(SixHourCandleQueue_Calculations),
        new BullAdapter(EightHourCandleQueue_Calculations),
        new BullAdapter(TwelveHourCandleQueue_Calculations),
        new BullAdapter(OneDayCandleQueue_Calculations),
        new BullAdapter(ThreeDayCandleQueue_Calculations),
        new BullAdapter(OneWeekCandleQueue_Calculations),
        new BullAdapter(OneMonthCandleQueue_Calculations),

        new BullAdapter(OneMinuteCandleQueue_Preprocessings),
        new BullAdapter(ThreeMinutesCandleQueue_Preprocessings),
        new BullAdapter(FiveMinutesCandleQueue_Preprocessings),
        new BullAdapter(FifteenMinutesCandleQueue_Preprocessings),
        new BullAdapter(ThirtyMinutesCandleQueue_Preprocessings),
        new BullAdapter(OneHourCandleQueue_Preprocessings),
        new BullAdapter(TwoHourCandleQueue_Preprocessings),
        new BullAdapter(FourHourCandleQueue_Preprocessings),
        new BullAdapter(SixHourCandleQueue_Preprocessings),
        new BullAdapter(EightHourCandleQueue_Preprocessings),
        new BullAdapter(TwelveHourCandleQueue_Preprocessings),
        new BullAdapter(OneDayCandleQueue_Preprocessings),
        new BullAdapter(ThreeDayCandleQueue_Preprocessings),
        new BullAdapter(OneWeekCandleQueue_Preprocessings),
        new BullAdapter(OneMonthCandleQueue_Preprocessings),
      ]
    });
  }
}